FORMAT: 1A
HOST: https://api.qr-id.info
# QRID REST API Documentation
# Group Главная

### Главная [GET  /]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Главная
    + Body
        {
            "message": "Hello World!"
        }



# Group Генератор

### Создать QR Code [GET  /generate/image/57561b4b-3b35-4db1-acb2-119b0693e143]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + barcolor: FFFFFF (string) - Цвет QR Code
    + backgroundcolor: 000000 (string) - Цвет Фона если не задан то прозрачный
    + scale: 5 (string) - Маштаб


### Создание меток [GET  /generate/]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + count: 2 (string) - Кол-во меток для генерации
    + type: ids (string) - Желаемый вид ответа "images", "mixed", 'ids'

+ Response 200 (application/json)
Создание меток type=images
    + Body
        [
            "https://qr-id.info/generate/image/5dfc2867-98d0-4293-9405-fb6cb68d8f77",
            "https://qr-id.info/generate/image/38326543-4a00-473a-bc40-a65a235db7f6"
        ]

+ Response 200 (application/json)
Создание меток type=mixed
    + Body
        [
            {
                "uuid": "https://qr-id.info/tag/c16a0c9d-ea3a-4069-9bd2-08918ee70e7e",
                "src": "https://qr-id.info/generate/image/c16a0c9d-ea3a-4069-9bd2-08918ee70e7e"
            },
            {
                "uuid": "https://qr-id.info/tag/30092e85-d5fe-4a69-b762-59507eb11367",
                "src": "https://qr-id.info/generate/image/30092e85-d5fe-4a69-b762-59507eb11367"
            }
        ]

+ Response 200 (application/json)
Создание меток type=ids
    + Body
        [
            "https://qr-id.info/tag/ee41773c-7d87-4aa3-9d58-d40b05d78e31",
            "https://qr-id.info/tag/2a400d46-8706-4867-89cc-d84f31a6ff15"
        ]



# Group Авторизация

### Авторизация [POST  /login]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + email: 16skala@gmail.com (string) - Адрес электронной почты
    + password: 123456 (string) - Пароль пользователя

+ Response 200 (application/json)
Авторизация
    + Body
        {
            "user": {
                "createAt": "2019-03-22T12:40:29.715Z",
                "deleteAt": null,
                "email": "16skala@gmail.com",
                "updateAt": "2019-03-22T12:40:29.715Z",
                "username": "Какая то компания"
            },
            "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0ZTczNzRiLTg2NmYtNDM4Yi05YjVlLThkZDIyMmQxMjQyOCIsImlhdCI6MTU1NDI5NjU3MywiZXhwIjoxNTU0OTQ0NTczfQ.BZgBec1WPcm5UWWEL5178p6RXN2a3rDr95xarfZ-Yfg"
        }

+ Response 500 (application/json)
Авторизация
    + Body
        {
            "field": "password",
            "err": "Не корректный пароль"
        }


### Регистрация [POST  /register]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + email: 16skala@gmail.com (string) - E-mail пользователя
    + password: 123456 (string) - Пароль пользователя
    + username: Какая то компания (string) - Название компании

+ Response 500 (application/json)
Ошибка Регистрации
    + Body
        {
            "err": "Пользователь с таким E-mail уже существует в БД"
        }

+ Response 200 (application/json)
Успешная регистрация
    + Body
        {
            "message": "Пользователь успешно зарегистрирован"
        }


### Получить информацию о пользоавателе [GET  /me]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Получить информацию о пользоавателе
    + Body
        {
            "email": "16skala@gmail.com",
            "id": "04e7374b-866f-438b-9b5e-8dd222d12428",
            "username": "Какая то компания"
        }


  + Headers

        Authorization: bearer token



# Group Категории

### Получить список категорий [GET  /category]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Получить список категорий
    + Body
        [
            {
                "createAt": "2019-04-04T19:55:47.264Z",
                "deleteAt": null,
                "id": "d7c0227b-08ed-4ed6-bd3c-9593e995e35b",
                "name": "Какое то название",
                "updateAt": "2019-04-04T19:55:47.264Z",
                "user": "04e7374b-866f-438b-9b5e-8dd222d12428"
            },
            {
                "createAt": "2019-03-22T12:40:35.039Z",
                "deleteAt": null,
                "id": "d78ec067-d1b3-499b-af5c-5946a10d2ee1",
                "name": "Категория 1",
                "position": 0,
                "updateAt": "2019-03-22T12:40:35.039Z",
                "user": "04e7374b-866f-438b-9b5e-8dd222d12428"
            },
            {
                "createAt": "2019-03-22T12:40:35.039Z",
                "deleteAt": null,
                "id": "5e446147-0ba8-4075-b6ce-71190bddf062",
                "name": "Категория 2",
                "position": 0,
                "updateAt": "2019-03-22T12:40:35.039Z",
                "user": "04e7374b-866f-438b-9b5e-8dd222d12428"
            }
        ]


### Создать [POST  /category]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + name: Категория 1 (string) - Название категории

+ Response 200 (application/json)
Создать
    + Body
        [
            {
                "createAt": "2019-04-04T20:11:03.741Z",
                "deleteAt": null,
                "id": "0ef9dea5-4106-4086-9513-536a1399c930",
                "name": "Категория 1",
                "updateAt": "2019-04-04T20:11:03.741Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            }
        ]


### Редактировать [PATCH  /category/{id}]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + name: Категория  2 (string) - Название категории

+ Response 200 (application/json)
Редактировать
    + Body
        {
            "createAt": "2019-04-04T20:11:03.741Z",
            "deleteAt": null,
            "id": "0ef9dea5-4106-4086-9513-536a1399c930",
            "name": "Категория  2",
            "updateAt": "2019-04-04T20:11:56.142Z",
            "user": "dd312560-5171-48bb-becf-fce408c4e532"
        }


### Удалить [DELETE  /category/{id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Удалить
    + Body
        {
            "createAt": "2019-04-04T20:11:03.741Z",
            "deleteAt": "2019-04-04T20:12:37.223Z",
            "id": "0ef9dea5-4106-4086-9513-536a1399c930",
            "name": "Категория  2",
            "updateAt": "2019-04-04T20:11:56.142Z",
            "user": "dd312560-5171-48bb-becf-fce408c4e532"
        }


  + Headers

        Authorization: bearer token



# Group Настройки каталога

### Создать харарактеристику категории [POST  /char_section/{category_id}]
  + Headers

        Authorization: bearer token


+ Response 500 (application/json)
Ошибка не верный тип
    + Body
        {
            "err": "Укажите один из допустимых типов: \"description\",\"characteristic\",\"files\",\"documentation\",\"faq\",\"forum\",\"issues\""
        }

+ Response 200 (application/json)
Создать харарактеристику категории
    + Body
        [
            {
                "createAt": "2019-04-05T12:26:37.541Z",
                "default_value": "Значение",
                "deleteAt": null,
                "id": "8802eef3-d063-4102-84a3-8c4b2394c579",
                "name": "Какая то настройка 123123123123123123100500",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 0,
                "title": "Заголовок",
                "type": "String",
                "updateAt": "2019-04-05T12:26:37.541Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            },
            {
                "createAt": "2019-04-05T13:53:10.360Z",
                "default_value": "Значение",
                "deleteAt": null,
                "id": "65b8d26f-a060-4730-8b83-b45f4f629d5f",
                "name": "Какая то настройка 123123123123123123100500",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 0,
                "title": "Заголовок",
                "type": "description",
                "updateAt": "2019-04-05T13:53:10.360Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            },
            {
                "createAt": "2019-04-04T20:37:25.710Z",
                "default_value": "<p>Еще какой то непонятный блок - А это его сраное описание</p>",
                "deleteAt": null,
                "id": "b5d5b385-2db6-4104-8f27-04778a8fba15",
                "name": "Описание",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 1,
                "title": "Еще какой то непонятный блок",
                "type": "description",
                "updateAt": "2019-04-04T20:37:25.710Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            },
            {
                "createAt": "2019-04-04T20:36:54.515Z",
                "default_value": "<p>Какая то срань</p>",
                "deleteAt": null,
                "id": "b4034842-b9ac-4be0-adaa-530def83159c",
                "name": "Описание",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 2,
                "title": "Данные",
                "type": "description",
                "updateAt": "2019-04-04T20:36:54.515Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            }
        ]


### Получить характеристики категории [GET  /char_product/{category_id}]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + type_section: description (string) - Тип настроек каталога

+ Response 200 (application/json)
Получить характеристики категории
    + Body
        [
            {
                "createAt": "2019-04-05T13:53:10.360Z",
                "default_value": "Значение",
                "deleteAt": null,
                "id": "65b8d26f-a060-4730-8b83-b45f4f629d5f",
                "name": "Какая то настройка 123123123123123123100500",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 1,
                "title": "Заголовок",
                "type": "description",
                "updateAt": "2019-04-05T13:53:10.360Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            },
            {
                "createAt": "2019-04-04T20:37:25.710Z",
                "default_value": "<p>Еще какой то непонятный блок - А это его сраное описание</p>",
                "deleteAt": null,
                "id": "b5d5b385-2db6-4104-8f27-04778a8fba15",
                "name": "Описание",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 2,
                "title": "Еще какой то непонятный блок",
                "type": "description",
                "updateAt": "2019-04-04T20:37:25.710Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            },
            {
                "createAt": "2019-04-04T20:36:54.515Z",
                "default_value": "<p>Какая то срань</p>",
                "deleteAt": null,
                "id": "b4034842-b9ac-4be0-adaa-530def83159c",
                "name": "Описание",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "position": 3,
                "title": "Данные",
                "type": "description",
                "updateAt": "2019-04-04T20:36:54.515Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            }
        ]


### Изменить характеристику категории [PATCH  /char_product/{id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Изменить характеристику категории
    + Body
        {
            "createAt": "2019-04-05T13:53:10.360Z",
            "default_value": "Значение",
            "deleteAt": null,
            "id": "65b8d26f-a060-4730-8b83-b45f4f629d5f",
            "name": "Какое то имя 1",
            "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
            "position": 1,
            "title": "Заголовок",
            "type": "description",
            "updateAt": "2019-04-05T13:53:10.360Z",
            "user": "dd312560-5171-48bb-becf-fce408c4e532"
        }


### Изменить очередность элементов [PATCH  /char_product/{category_id}/position]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Изменить очередность элементов
    + Body
        [
            {
                "err": "Не удалось найти поле [id] или [position]",
                "element": {
                    "position": 1
                }
            },
            {
                "deleted": 0,
                "errors": 0,
                "inserted": 0,
                "replaced": 0,
                "skipped": 0,
                "unchanged": 1
            },
            {
                "deleted": 0,
                "errors": 0,
                "inserted": 0,
                "replaced": 1,
                "skipped": 0,
                "unchanged": 0
            }
        ]


  + Headers

        Authorization: bearer token



# Group Позиции

### Получить список позиций [GET  /catalog/{category_id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Получить список позиций
    + Body
        [
            {
                "createAt": "2019-04-05T16:38:46.821Z",
                "deleteAt": null,
                "id": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "name": "Позиция",
                "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                "updateAt": "2019-04-05T16:38:46.821Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532"
            }
        ]


### Получить одну позицию [GET  /catalog/item/{id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Получить одну позицию
    + Body
        {
            "chars_product": [
                {
                    "createAt": "2019-04-05T15:28:23.423Z",
                    "default_value": [],
                    "deleteAt": null,
                    "id": "1682c89b-4638-4429-8cab-faad3fe316ba",
                    "list_values": [
                        "фывфыв",
                        "фЫВ",
                        "ФЫ",
                        "в",
                        "ФыВ",
                        "фЫ",
                        "вФ",
                        "ы",
                        "В"
                    ],
                    "name": "Чекбоксы",
                    "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
                    "position": 0,
                    "title": "",
                    "type": "check",
                    "updateAt": "2019-04-05T15:28:23.423Z",
                    "user": "dd312560-5171-48bb-becf-fce408c4e532",
                    "values": [
                        {
                            "createAt": "2019-04-05T17:08:28.410Z",
                            "deleteAt": null,
                            "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                            "id": "6cb1ce45-9d5e-4f70-ae2a-4fcd48cd8ccb",
                            "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                            "updateAt": "2019-04-05T17:08:28.410Z",
                            "user": "dd312560-5171-48bb-becf-fce408c4e532",
                            "value": "Значение 2"
                        },
                        {
                            "createAt": "2019-04-05T17:08:23.126Z",
                            "deleteAt": null,
                            "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                            "id": "a95e7979-a80f-4a33-9634-213629d97f33",
                            "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                            "updateAt": "2019-04-05T17:08:23.126Z",
                            "user": "dd312560-5171-48bb-becf-fce408c4e532",
                            "value": "Значение 1"
                        }
                    ]
                }
            ],
            "createAt": "2019-04-05T16:38:46.821Z",
            "deleteAt": null,
            "id": "3ec0b656-ee11-47ec-b53e-6860af371321",
            "name": "Какое то имя 12312312312312123",
            "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
            "position": 1,
            "updateAt": "2019-04-05T16:38:46.821Z",
            "user": "dd312560-5171-48bb-becf-fce408c4e532"
        }


### Редактировать позицию [PATCH  /catalog/{category_id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Редактировать позицию
    + Body
        {
            "createAt": "2019-04-05T16:38:46.821Z",
            "deleteAt": null,
            "id": "3ec0b656-ee11-47ec-b53e-6860af371321",
            "name": "Какое то имя 12312312312312123",
            "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
            "position": 1,
            "updateAt": "2019-04-05T16:38:46.821Z",
            "user": "dd312560-5171-48bb-becf-fce408c4e532"
        }


### Создать позицию [POST  /catalog/{category_id}]
  + Headers

        Authorization: bearer token


+ Attributes (object)
    + name: Позиция (string) - Название позиции

+ Response 200 (application/json)
Создать позицию
    + Body
        {
            "createAt": "2019-04-05T16:38:46.821Z",
            "deleteAt": null,
            "id": "3ec0b656-ee11-47ec-b53e-6860af371321",
            "name": "Позиция",
            "parent": "7c7bf0a2-4a8a-4c6e-86b3-6ff38b96d12f",
            "updateAt": "2019-04-05T16:38:46.821Z",
            "user": "dd312560-5171-48bb-becf-fce408c4e532"
        }


  + Headers

        Authorization: bearer token



# Group Значения позиций

### Создать значение характеристики [POST  /char_product_value/{catalog_id}/{char_product_id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Создать значение характеристики
    + Body
        [
            {
                "createAt": "2019-04-05T17:08:28.410Z",
                "deleteAt": null,
                "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "id": "6cb1ce45-9d5e-4f70-ae2a-4fcd48cd8ccb",
                "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                "updateAt": "2019-04-05T17:08:28.410Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532",
                "value": "Значение 2"
            },
            {
                "createAt": "2019-04-05T17:08:23.126Z",
                "deleteAt": null,
                "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "id": "a95e7979-a80f-4a33-9634-213629d97f33",
                "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                "updateAt": "2019-04-05T17:08:23.126Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532",
                "value": "Значение 1"
            }
        ]


### Редактировать значение [PATCH  /char_product_value/{id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Редактировать значение
    + Body
        [
            {
                "createAt": "2019-04-05T17:08:28.410Z",
                "deleteAt": null,
                "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "id": "6cb1ce45-9d5e-4f70-ae2a-4fcd48cd8ccb",
                "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                "updateAt": "2019-04-05T17:08:28.410Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532",
                "value": "Характеристика 100500"
            },
            {
                "createAt": "2019-04-05T17:08:23.126Z",
                "deleteAt": null,
                "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "id": "a95e7979-a80f-4a33-9634-213629d97f33",
                "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                "updateAt": "2019-04-05T17:08:23.126Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532",
                "value": "Значение 1"
            }
        ]


### Получить список позиции [GET  /char_product_value/{catalog_id}]
  + Headers

        Authorization: bearer token


+ Response 200 (application/json)
Получить список позиции
    + Body
        [
            {
                "createAt": "2019-04-05T17:08:28.410Z",
                "deleteAt": null,
                "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "id": "6cb1ce45-9d5e-4f70-ae2a-4fcd48cd8ccb",
                "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                "updateAt": "2019-04-05T17:08:28.410Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532",
                "value": "Характеристика 100500"
            },
            {
                "createAt": "2019-04-05T17:08:23.126Z",
                "deleteAt": null,
                "dependencies": "3ec0b656-ee11-47ec-b53e-6860af371321",
                "id": "a95e7979-a80f-4a33-9634-213629d97f33",
                "parent": "1682c89b-4638-4429-8cab-faad3fe316ba",
                "updateAt": "2019-04-05T17:08:23.126Z",
                "user": "dd312560-5171-48bb-becf-fce408c4e532",
                "value": "Значение 1"
            }
        ]


  + Headers

        Authorization: bearer token


